'------------------------------------------------------------------------------
' <auto-generated>
'     這段程式碼是由工具產生的。
'     執行階段版本:4.0.30319.42000
'
'     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
'     變更將會遺失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    '類別透過 ResGen 或 Visual Studio 這類工具。
    '若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    '(利用 /str 選項)，或重建您的 VS 專案。
    '''<summary>
    '''  用於查詢當地語系化字串等的強類型資源類別。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  傳回這個類別使用的快取的 ResourceManager 執行個體。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("KRAKEN.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        '''  使用這個強類型資源類別的資源查閱。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property _3主遊戲畫面() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_3主遊戲畫面", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property karken() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("karken", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 System.IO.MemoryStream 的類型 System.IO.UnmanagedMemoryStream 當地語系化資源。
        '''</summary>
        Friend ReadOnly Property maingame() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("maingame", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 System.IO.MemoryStream 的類型 System.IO.UnmanagedMemoryStream 當地語系化資源。
        '''</summary>
        Friend ReadOnly Property maze() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("maze", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 System.IO.MemoryStream 的類型 System.IO.UnmanagedMemoryStream 當地語系化資源。
        '''</summary>
        Friend ReadOnly Property paper() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("paper", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property sketch_1672920127022() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sketch-1672920127022", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property skull() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("skull", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property skull2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("skull2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property skull3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("skull3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 System.IO.MemoryStream 的類型 System.IO.UnmanagedMemoryStream 當地語系化資源。
        '''</summary>
        Friend ReadOnly Property start() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("start", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property start_button() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("start_button", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property START畫面_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("START畫面_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property TEAM() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TEAM", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property vk() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vk", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 主遊戲背景() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("主遊戲背景", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 公主說明() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("公主說明", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 公主說明_傳送鍵() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("公主說明_傳送鍵", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 困住的海螺_籠子() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("困住的海螺_籠子", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 地板() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("地板", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 平台_短() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("平台_短", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 平台_長() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("平台_長", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 木桶() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("木桶", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 毒液_12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("毒液_12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 毒液_2a() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("毒液_2a", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 毒液_上_有底() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("毒液_上_有底", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 毒液_下_有底() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("毒液_下_有底", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 毒液_地板_長() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("毒液_地板_長", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 海螺() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("海螺", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 移動平台_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("移動平台_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 結算失敗畫面() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("結算失敗畫面", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 結算失敗畫面_按鍵() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("結算失敗畫面_按鍵", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 結算成功_一星() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("結算成功_一星", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 結算成功_三星() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("結算成功_三星", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 結算成功_二星() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("結算成功_二星", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 結算成功_按鍵() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("結算成功_按鍵", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 維京人_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("維京人_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 舵() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("舵", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 解碼遊戲_背景() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("解碼遊戲_背景", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 解碼遊戲_選擇紙條_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("解碼遊戲_選擇紙條_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 迷宮遊戲_框_a單邊_上() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("迷宮遊戲_框_a單邊_上", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 迷宮遊戲_框_a單邊_下() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("迷宮遊戲_框_a單邊_下", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 迷宮遊戲_框_a單邊_右() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("迷宮遊戲_框_a單邊_右", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 迷宮遊戲_框_a單邊_左() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("迷宮遊戲_框_a單邊_左", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 迷宮遊戲_框_背景() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("迷宮遊戲_框_背景", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 迷宮遊戲_牆() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("迷宮遊戲_牆", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 迷宮遊戲_終點() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("迷宮遊戲_終點", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 迷宮遊戲_維京人() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("迷宮遊戲_維京人", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 開海螺的鑰匙() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("開海螺的鑰匙", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 魚() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("魚", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 魚1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("魚1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 魚2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("魚2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 魚3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("魚3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
